package com.canyugan.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import com.alibaba.fastjson.JSONObject;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

/**
 * 是否管理员验证服务
 * @author 
 */
@Service
public class AuthService 
{
	private static final Logger LOG = LoggerFactory.getLogger(AuthService.class);
	@Value("${host}")
	private String host;
	
	public  String sendUserService(OkHttpClient okHttpClientPool)
	{
		String user_auth_result = null;
		try {
//			LOG.info("-->【  user_id验证服务开始调用 】");
//			Request request = new Request.Builder().url(host).get().build();
//			Response response = okHttpClientPool.newCall(request).execute();
//			if (response.isSuccessful()) {
//				ResponseBody body = response.body();
//				LOG.info("-->【 sendUserService 请求成功】");
//				user_auth_result =  new String(body.bytes());
//				//处理result 返回nickName
				return "[\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-007-005-线上闭环子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-007-005\",\n" + 
						"        \"projectName\":\"线上闭环子项\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-007-004-人机协作深化子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-007-004\",\n" + 
						"        \"projectName\":\"人机协作深化子项\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-016-北极星项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-016\",\n" + 
						"        \"projectName\":\"北极星项目\",\n" + 
						"        \"projectPerson\":\"张学智\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-015-004-消费信贷智能授信1期子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-015-004\",\n" + 
						"        \"projectName\":\"消费信贷智能授信1期子项\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-015-003-鹰眼申请反欺诈子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-015-003\",\n" + 
						"        \"projectName\":\"鹰眼申请反欺诈子项\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-015-002-鹰眼一期交易反欺诈子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-015-002\",\n" + 
						"        \"projectName\":\"鹰眼一期交易反欺诈子项\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-015-001-智眸催收外呼机器人子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-015-001\",\n" + 
						"        \"projectName\":\"智眸催收外呼机器人子项\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-014-数据中台一期项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-014\",\n" + 
						"        \"projectName\":\"数据中台一期项目\",\n" + 
						"        \"projectPerson\":\"范志鸿\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-013-消费者权益保护管理平台建设项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-013\",\n" + 
						"        \"projectName\":\"消费者权益保护管理平台建设项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-012-001-个金催收系统惠民贷电催子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-012-001\",\n" + 
						"        \"projectName\":\"个金催收系统惠民贷电催子项\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-115-测试管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-115\",\n" + 
						"        \"projectName\":\"测试管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"龚伟奇\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-114-基础技术支撑系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-114\",\n" + 
						"        \"projectName\":\"基础技术支撑系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"林锥\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-113-网络发卡系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-113\",\n" + 
						"        \"projectName\":\"网络发卡系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"季阳\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-112-PDA办卡及销售管理系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-112\",\n" + 
						"        \"projectName\":\"PDA办卡及销售管理系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-111-运营业务监控系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-111\",\n" + 
						"        \"projectName\":\"运营业务监控系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-110-数字生活系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-110\",\n" + 
						"        \"projectName\":\"数字生活系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"马欢\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-109-账务服务系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-109\",\n" + 
						"        \"projectName\":\"账务服务系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赫孟如\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-011-移动前端框架项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-011\",\n" + 
						"        \"projectName\":\"移动前端框架项目\",\n" + 
						"        \"projectPerson\":\"赵加正\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-010-002-新餐饮建设商户部分子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-010-002\",\n" + 
						"        \"projectName\":\"新餐饮建设商户部分子项\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-010-001-新餐饮建设子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-010-001\",\n" + 
						"        \"projectName\":\"新餐饮建设子项\",\n" + 
						"        \"projectPerson\":\"马欢\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-009-智能签到项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-009\",\n" + 
						"        \"projectName\":\"智能签到项目\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-008-商户服务平台重构项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-008\",\n" + 
						"        \"projectName\":\"商户服务平台重构项目\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-007-003-互联网平台子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-007-003\",\n" + 
						"        \"projectName\":\"互联网平台子项\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-007-002-智能IVR重构子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-007-002\",\n" + 
						"        \"projectName\":\"智能IVR重构子项\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-007-001-服务策略及管理配置子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-007-001\",\n" + 
						"        \"projectName\":\"服务策略及管理配置子项\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-006-002-智能营销平台子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-006-002\",\n" + 
						"        \"projectName\":\"智能营销平台子项\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-006-001-消费金融引擎二期子项\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-006-001\",\n" + 
						"        \"projectName\":\"消费金融引擎二期子项\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-005-E办卡智能营销终端五代设备选型项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-005\",\n" + 
						"        \"projectName\":\"E办卡智能营销终端五代设备选型项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-004-销售管理系统重构项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-004\",\n" + 
						"        \"projectName\":\"销售管理系统重构项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-001-001-PDA中间件系统重构上云\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-001-001\",\n" + 
						"        \"projectName\":\"PDA中间件系统重构上云\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-108-买单吧商户版APP系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-108\",\n" + 
						"        \"projectName\":\"买单吧商户版APP系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-107-移动互联基础金融系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-107\",\n" + 
						"        \"projectName\":\"移动互联基础金融系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-106-新商户管理系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-106\",\n" + 
						"        \"projectName\":\"新商户管理系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-105-新支付核心系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-105\",\n" + 
						"        \"projectName\":\"新支付核心系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-104-消费信贷系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-104\",\n" + 
						"        \"projectName\":\"消费信贷系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-103-Touda-Stream分布式流计算系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-103\",\n" + 
						"        \"projectName\":\"Touda-Stream分布式流计算系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈鹏\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-102-电子鉴权系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-102\",\n" + 
						"        \"projectName\":\"电子鉴权系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-101-信用卡支付安全验证系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-101\",\n" + 
						"        \"projectName\":\"信用卡支付安全验证系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-100-统一缴费系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-100\",\n" + 
						"        \"projectName\":\"统一缴费系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-099-智能硬件接入系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-099\",\n" + 
						"        \"projectName\":\"智能硬件接入系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈鹏\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-098-反欺诈实时交易监控系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-098\",\n" + 
						"        \"projectName\":\"反欺诈实时交易监控系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"黄晓俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-097-权益兑换系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-097\",\n" + 
						"        \"projectName\":\"权益兑换系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赫孟如\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-096-分行电子化进件系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-096\",\n" + 
						"        \"projectName\":\"分行电子化进件系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-095-中文信息检索系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-095\",\n" + 
						"        \"projectName\":\"中文信息检索系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-094-Athena对话机器人系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-094\",\n" + 
						"        \"projectName\":\"Athena对话机器人系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈鹏\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-093-客服人机协作维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-093\",\n" + 
						"        \"projectName\":\"客服人机协作维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-092-新一代移动互联商城系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-092\",\n" + 
						"        \"projectName\":\"新一代移动互联商城系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"岑斌\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-091-新一代移动互联运营监控中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-091\",\n" + 
						"        \"projectName\":\"新一代移动互联运营监控中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-090-新一代移动互联用户中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-090\",\n" + 
						"        \"projectName\":\"新一代移动互联用户中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"岑斌\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-089-新一代移动互联数据服务平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-089\",\n" + 
						"        \"projectName\":\"新一代移动互联数据服务平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"林锥\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-088-新一代移动互联权益中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-088\",\n" + 
						"        \"projectName\":\"新一代移动互联权益中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"李峰\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-087-新一代移动互联活动中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-087\",\n" + 
						"        \"projectName\":\"新一代移动互联活动中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"李峰\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-086-新一代移动互联风控平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-086\",\n" + 
						"        \"projectName\":\"新一代移动互联风控平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-085-新一代移动互联订单中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-085\",\n" + 
						"        \"projectName\":\"新一代移动互联订单中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"李峰\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-084-新一代交互网关平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-084\",\n" + 
						"        \"projectName\":\"新一代交互网关平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-083-智能文本机器人系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-083\",\n" + 
						"        \"projectName\":\"智能文本机器人系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-082-人工智能中枢系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-082\",\n" + 
						"        \"projectName\":\"人工智能中枢系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-081-应收应付系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-081\",\n" + 
						"        \"projectName\":\"应收应付系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赫孟如\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-080-小程序应用系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-080\",\n" + 
						"        \"projectName\":\"小程序应用系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"季阳\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-079-荣誉体系管理维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-079\",\n" + 
						"        \"projectName\":\"荣誉体系管理维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈鹏\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-078-客服人力管理系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-078\",\n" + 
						"        \"projectName\":\"客服人力管理系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-077-智能运营平台客户服务标识维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-077\",\n" + 
						"        \"projectName\":\"智能运营平台客户服务标识维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-076-智能运营平台主动服务维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-076\",\n" + 
						"        \"projectName\":\"智能运营平台主动服务维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-075-设备指纹系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-075\",\n" + 
						"        \"projectName\":\"设备指纹系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赵加正\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-074-还款服务系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-074\",\n" + 
						"        \"projectName\":\"还款服务系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赫孟如\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-073-智能客服平台知识库维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-073\",\n" + 
						"        \"projectName\":\"智能客服平台知识库维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-072-智能客服平台客服直播模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-072\",\n" + 
						"        \"projectName\":\"智能客服平台客服直播模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-071-智能客服平台智能问答机器人模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-071\",\n" + 
						"        \"projectName\":\"智能客服平台智能问答机器人模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-070-运营管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-070\",\n" + 
						"        \"projectName\":\"运营管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"丁卫星\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-069-在线考试系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-069\",\n" + 
						"        \"projectName\":\"在线考试系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-068-O2O统一模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-068\",\n" + 
						"        \"projectName\":\"O2O统一模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"马欢\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-067-消息中心模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-067\",\n" + 
						"        \"projectName\":\"消息中心模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-066-我的信用卡模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-066\",\n" + 
						"        \"projectName\":\"我的信用卡模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-065-微信小I模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-065\",\n" + 
						"        \"projectName\":\"微信小I模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"季阳\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-064-网站页面模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-064\",\n" + 
						"        \"projectName\":\"网站页面模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-063-网络发卡模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-063\",\n" + 
						"        \"projectName\":\"网络发卡模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"季阳\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-062-数据采集模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-062\",\n" + 
						"        \"projectName\":\"数据采集模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-061-买单吧APP维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-061\",\n" + 
						"        \"projectName\":\"买单吧APP维护优化项目\",\n" + 
						"        \"projectPerson\":\"赵加正\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-060-积分乐园模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-060\",\n" + 
						"        \"projectName\":\"积分乐园模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"马欢\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-059-电子凭证系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-059\",\n" + 
						"        \"projectName\":\"电子凭证系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"马欢\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-058-超级账户模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-058\",\n" + 
						"        \"projectName\":\"超级账户模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-057-MOS移动办公平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-057\",\n" + 
						"        \"projectName\":\"MOS移动办公平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-056-文件服务中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-056\",\n" + 
						"        \"projectName\":\"文件服务中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱生虎\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-055-网上报销系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-055\",\n" + 
						"        \"projectName\":\"网上报销系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-054-双速研发管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-054\",\n" + 
						"        \"projectName\":\"双速研发管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"何华\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-053-网站招聘模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-053\",\n" + 
						"        \"projectName\":\"网站招聘模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"朱前线\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-052-ESB系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-052\",\n" + 
						"        \"projectName\":\"ESB系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"王莹\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-051-内网维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-051\",\n" + 
						"        \"projectName\":\"内网维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-050-买单吧客户服务中心维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-050\",\n" + 
						"        \"projectName\":\"买单吧客户服务中心维护优化项目\",\n" + 
						"        \"projectPerson\":\"范琼俊\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-049-CQM录音录屏质检平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-049\",\n" + 
						"        \"projectName\":\"CQM录音录屏质检平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-048-智能感知系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-048\",\n" + 
						"        \"projectName\":\"智能感知系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈鹏\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-047-统一权限平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-047\",\n" + 
						"        \"projectName\":\"统一权限平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-046-工作效率系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-046\",\n" + 
						"        \"projectName\":\"工作效率系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-045-TOUDA平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-045\",\n" + 
						"        \"projectName\":\"TOUDA平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"林锥\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-044-额度中枢系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-044\",\n" + 
						"        \"projectName\":\"额度中枢系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-043-风险CDA对外服务系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-043\",\n" + 
						"        \"projectName\":\"风险CDA对外服务系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-042-统一沟通和内容管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-042\",\n" + 
						"        \"projectName\":\"统一沟通和内容管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-041-双向短信平台模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-041\",\n" + 
						"        \"projectName\":\"双向短信平台模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-040-梦网平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-040\",\n" + 
						"        \"projectName\":\"梦网平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-039-流量管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-039\",\n" + 
						"        \"projectName\":\"流量管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-038-电子账单管理模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-038\",\n" + 
						"        \"projectName\":\"电子账单管理模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-037-电子邮件平台模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-037\",\n" + 
						"        \"projectName\":\"电子邮件平台模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"唐煜舟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-036-电子传真平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-036\",\n" + 
						"        \"projectName\":\"电子传真平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-035-短信服务平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-035\",\n" + 
						"        \"projectName\":\"短信服务平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-034-老商户管理系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-034\",\n" + 
						"        \"projectName\":\"老商户管理系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"王立\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-033-机构部电子效率手册系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-033\",\n" + 
						"        \"projectName\":\"机构部电子效率手册系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-032-办公综合管理平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-032\",\n" + 
						"        \"projectName\":\"办公综合管理平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-031-客户之声系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-031\",\n" + 
						"        \"projectName\":\"客户之声系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-030-PRM报警模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-030\",\n" + 
						"        \"projectName\":\"PRM报警模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-029-统一保险销售平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-029\",\n" + 
						"        \"projectName\":\"统一保险销售平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-028-新一代eHR系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-028\",\n" + 
						"        \"projectName\":\"新一代eHR系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-027-SAP系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-027\",\n" + 
						"        \"projectName\":\"SAP系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-026-薪酬绩效外挂模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-026\",\n" + 
						"        \"projectName\":\"薪酬绩效外挂模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-025-收单交易风险监控系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-025\",\n" + 
						"        \"projectName\":\"收单交易风险监控系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"赫孟如\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-024-讯飞语音分析维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-024\",\n" + 
						"        \"projectName\":\"讯飞语音分析维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-023-客服自动语音应答系统IVR维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-023\",\n" + 
						"        \"projectName\":\"客服自动语音应答系统IVR维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-022-SIP话务平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-022\",\n" + 
						"        \"projectName\":\"SIP话务平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"施泉刚\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-021-卡中心流程平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-021\",\n" + 
						"        \"projectName\":\"卡中心流程平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"张震\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-020-e办卡智能营销系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-020\",\n" + 
						"        \"projectName\":\"e办卡智能营销系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"秦炜\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-019-收费平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-019\",\n" + 
						"        \"projectName\":\"收费平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-018-NFTM非金融交易监控系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-018\",\n" + 
						"        \"projectName\":\"NFTM非金融交易监控系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-017-TFM交易监控操作平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-017\",\n" + 
						"        \"projectName\":\"TFM交易监控操作平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-016-客户信息管理模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-016\",\n" + 
						"        \"projectName\":\"客户信息管理模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"卜安安\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-015-商户管理平台3.0维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-015\",\n" + 
						"        \"projectName\":\"商户管理平台3.0维护优化项目\",\n" + 
						"        \"projectPerson\":\"于晓亮\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-014-智能在线客服模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-014\",\n" + 
						"        \"projectName\":\"智能在线客服模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-013-外部征信模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-013\",\n" + 
						"        \"projectName\":\"外部征信模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-012-运营平台基础平台模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-012\",\n" + 
						"        \"projectName\":\"运营平台基础平台模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-011-运营平台制卡模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-011\",\n" + 
						"        \"projectName\":\"运营平台制卡模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-010-运营平台争议模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-010\",\n" + 
						"        \"projectName\":\"运营平台争议模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-009-运营平台电销模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-009\",\n" + 
						"        \"projectName\":\"运营平台电销模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-008-运营平台客服模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-008\",\n" + 
						"        \"projectName\":\"运营平台客服模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"陈永伟\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-007-运营平台案调模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-007\",\n" + 
						"        \"projectName\":\"运营平台案调模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-006-运营平台催收模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-006\",\n" + 
						"        \"projectName\":\"运营平台催收模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-005-运营平台信审模块维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-005\",\n" + 
						"        \"projectName\":\"运营平台信审模块维护优化项目\",\n" + 
						"        \"projectPerson\":\"顾一帆\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-004-地理信息平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-004\",\n" + 
						"        \"projectName\":\"地理信息平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"吴峻\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-003-即时临调维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-003\",\n" + 
						"        \"projectName\":\"即时临调维护优化项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-002-报表服务平台维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-002\",\n" + 
						"        \"projectName\":\"报表服务平台维护优化项目\",\n" + 
						"        \"projectPerson\":\"曹瑞\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-WH-2019-001-总行系统维护优化项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-WH-2019-001\",\n" + 
						"        \"projectName\":\"总行系统维护优化项目\",\n" + 
						"        \"projectPerson\":\"张庆丽\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-003-网络发卡新模式\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-003\",\n" + 
						"        \"projectName\":\"网络发卡新模式\",\n" + 
						"        \"projectPerson\":\"季阳\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-002-运营业务监控项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-002\",\n" + 
						"        \"projectName\":\"运营业务监控项目\",\n" + 
						"        \"projectPerson\":\"所晶\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    },\n" + 
						"    {\n" + 
						"        \"jiraProjectName\":\"PJ-LX-2019-001-云上卡中心项目\",\n" + 
						"        \"projectCodeNum\":\"PJ-LX-2019-001\",\n" + 
						"        \"projectName\":\"云上卡中心项目\",\n" + 
						"        \"projectPerson\":\"杨晓冬\",\n" + 
						"        \"projectStatus\":\"--\",\n" + 
						"        \"s1\":\"--\",\n" + 
						"        \"s2\":\"--\",\n" + 
						"        \"s3\":\"--\"\n" + 
						"    }\n" + 
						"]";
//			} else {
//				LOG.info("-->【 sendUserService 请求不成功 】");
		
			
			
		} catch (Exception e) {
			LOG.info("-->【 user_id验证服务调用出错，错误信息：" + e.getMessage() + "】");
			user_auth_result = null;
		}
		return user_auth_result;
	}
}

